# Netlify configuration for Next.js deployment
[build]
  command = "npm install && npm run build && ls -la .next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_EXPERIMENTAL_SERVERLESS_TRACE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://xmnghciitiefbwxzhgrw.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtbmdoY2lpdGllZmJ3eHpoZ3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjM0NzMsImV4cCI6MjA2OTI5OTQ3M30.dIeGonQS9a0ZhFo5WVYj1zMxtmm5juE35oCJSMm62a4"